### ISSUE TITLE
Előtörlesztés díja

### ISSUE THREAD

**Issue by laszlopapai** [csaba504/hitel_torleszto_kalkulator#1]
Tetszik az alkalmazás! Az előtörlesztéses részhez viszont találtam egy érdekes példát.

Tegyük fel, hogy 10 000-et szeretne előtörleszteni a tőketartozásból, és 1% a díja.
Tehát ebben az esetben 10 000 * 0.01 = 100 az előtörlesztés díja. Vagyis őszesen 10 100-at kell fizetni.

Ha vissza helyettesítek a képletbe, kevesebbre jön ki a díj levonása utáni összeg: 
https://github.com/csaba504/hitel_torleszto_kalkulator/blob/de1580f788cce4a7643bdb07402ed7f7818653ad/js/my.js#L260
add - (add * rate) -> 10 100 - (10 100 * 0.01) = 9 999
Ha így számol az előtörlesztés díjára is rá lesz számolva az 1% (előtörlesztés költsége). Ezzel le lehet választani: 
`add = add / (1.0 + rate)`

**Comment by csaba504** [comment]
Szia,

Jogos az észrevétel, javítva lett!
