### ISSUE TITLE
[Feature Request] Alapadatok és törlesztők lokális tárolása 

### ISSUE THREAD

**Issue by iabukai** [csaba504/hitel_torleszto_kalkulator#2]
- Atom lenne ha visszamegyek az oldalra akkor cookieból vagy valami lokális fájlból visszatöltődnének az adatok, nem kellene browseolgatnom a lementett fileom után.

**Comment by csaba504** [comment]
Szia,

Belekerült egy funkció, hogy könnyen lehessen a böngészőbe is elmenteni az adatokat. 
Használjátok egészséggel!
