### ISSUE TITLE
Összesen fizetett duplan szamol

### ISSUE THREAD

**Issue by reczuprik** [csaba504/hitel_torleszto_kalkulator#3]
Szia!
koszi a kalkulatort
az eszrevetelem az lenne, hogy Kamatok és költségek resz is szamol a pl az elotorlesztes dijaval, Egyéb kiadások is szamol ezzel , igy ha jol latom vegeredmenyben ez a dij ketszer van hozzaadva

**Comment by csaba504** [comment]
Szia,

Megnéztem részletesen.
Köszönöm szépen a jelzést! Igazad van!
Találtam még mellette egy másik hibát is azt is javítottam!
